export {
  APP_DIR,
  APP_LANGUAGE,
  APP_LANGUAGES,
  applyDocumentLanguage,
  getAppLanguage,
  getLanguageSnapshot,
  initLanguageFromStorage,
  jobStatusLabel,
  jobTypeLabel,
  messages,
  setAppLanguage,
  subscribeLanguage,
  t,
  useLanguage,
  type AppLanguage,
  type MessageCatalog,
  type TextDirection,
  type UseLanguageResult,
} from './i18n/index.ts'
