name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend:
    uses: ./.github/workflows/ci-backend.yml

  frontend:
    uses: ./.github/workflows/ci-frontend.yml
